---
- name: Assert platform is supported
  tags: heka
  assert:
    that:
      - ansible_os_family in heka_supported_platforms


- name: Load version vars
  tags: heka
  with_first_found:
    - ../vars/versions/{{ ansible_os_family }}/{{ heka_version }}.yml
    - ../vars/versions/default.yml
  include_vars: "{{ item }}"


- name: Assert version vars
  tags: heka
  assert:
    that:
      - heka_install_filename_sha256sum not in (None, "")


- name: Include OS specific vars
  tags: heka
  include_vars: "{{ ansible_os_family }}.yml"


- name: Download heka
  tags: heka
  sudo: no
  local_action: get_url
    dest={{ util_persistent_data_path_local }}/{{ heka_install_filename }}
    url={{ heka_mirror }}/v{{ heka_version }}/{{ heka_install_filename }}
    mode=0644
    sha256sum={{ heka_install_filename_sha256sum }}

- name: Upload heka
  tags: heka
  sudo: yes
  copy:
    src={{ util_persistent_data_path_local }}/{{ heka_install_filename }}
    dest={{ util_persistent_data_path_remote }}/{{ heka_install_filename }}
    owner=0
    group=0
    mode=0644


- include: Debian.yml
  tags: heka
  when: ansible_os_family == 'Debian'

- include: RedHat.yml
  tags: heka
  when: ansible_os_family == 'RedHat'


- name: Install hekad directories
  tags: heka
  sudo: yes
  with_items:
    - "{{ heka_hekad_etc_dir }}"
    - "{{ heka_hekad_base_dir }}/dashboard"
  file:
    state=directory
    owner=0
    group=0
    mode=0755
    dest={{ item }}


- name: Install hekad configuration
  tags: heka
  sudo: yes
  notify: service restart hekad
  template:
    src=hekad.toml.j2
    dest={{ heka_hekad_etc_dir }}/hekad.toml
    owner=0
    group=0
    mode=0644

- name: Install heka configuration (inputs)
  tags: heka
  sudo: yes
  notify: service restart hekad
  with_items: heka_inputs
  template:
    src=hekad_{{ item.type }}.toml.j2
    dest={{ heka_hekad_etc_dir }}/{{ item.name }}.toml
    owner=0
    group=0
    mode=0644

- name: Install heka configuration (outputs)
  tags: heka
  sudo: yes
  notify: service restart hekad
  with_items: heka_outputs
  template:
    src=hekad_{{ item.type }}.toml.j2
    dest={{ heka_hekad_etc_dir }}/{{ item.name }}.toml
    owner=0
    group=0
    mode=0644


- name: Ensure heka service
  tags: heka
  sudo: yes
  service:
    state=started
    enabled=yes
    name=hekad
