---
- name: Assert platform is supported
  tags: heka
  assert:
    that:
      - ansible_os_family in ['Debian', 'RedHat']


- name: Load version vars
  tags: heka
  with_first_found:
    - ../vars/versions/{{ ansible_os_family }}/{{ heka_version }}.yml
    - ../vars/versions/default.yml
  include_vars: "{{ item }}"


- name: Assert version vars
  tags: heka
  assert:
    that:
      - heka_install_filename_sha256sum not in (None, "")


- name: Include OS specific vars
  include_vars: "{{ ansible_os_family }}.yml"
  tags: heka


- name: Install local ansible data path directory (local)
  tags: heka
  local_action: file
    state=directory
    owner=0
    group=0
    mode=2777
    dest={{ local_ansible_data_path }}

- name: Download heka (local)
  tags: heka
  sudo: no
  local_action: get_url
    dest={{ local_ansible_data_path }}/{{ heka_install_filename }}
    url={{ heka_mirror }}/v{{ heka_version }}/{{ heka_install_filename }}
    mode=0644
    sha256sum={{ heka_install_filename_sha256sum }}


- name: Update apt package cache
  tags: heka
  when: ansible_os_family == 'Debian'
  apt:
    update_cache=yes
    cache_valid_time=3600

- include: selinux.yml
  tags: heka

- name: Install required packages
  tags: heka
  with_items: heka_package_list
  action: "{{ ansible_pkg_mgr }} state=installed name={{ item }}"


- name: Install remote ansible data path directory
  tags: heka
  file:
    state=directory
    dest={{ remote_ansible_data_path }}

- name: Syncronize heka installation package
  tags: heka
  synchronize:
    checksum=true
    mode=push
    src={{ local_ansible_data_path }}/{{ heka_install_filename }}
    dest={{ remote_ansible_data_path }}/{{ heka_install_filename }}


- include: Debian.yml
  tags: heka
  when: ansible_os_family == 'Debian'

- include: RedHat.yml
  tags: heka
  when: ansible_os_family == 'RedHat'


- name: Install hekad directories
  tags: heka
  with_items:
    - "{{ heka_hekad_etc_dir }}"
    - "{{ heka_hekad_base_dir }}/dashboard"
  file:
    state=directory
    owner=0
    group=0
    mode=0755
    dest={{ item }}


- name: Install hekad configuration
  tags: heka
  notify: service restart hekad
  template:
    src=hekad.toml.j2
    dest={{ heka_hekad_etc_dir }}/hekad.toml
    owner=0
    group=0
    mode=0644

- name: Install heka configuration (inputs)
  tags: heka
  notify: service restart hekad
  with_items: heka_inputs
  template:
    src=hekad_{{ item.type }}.toml.j2
    dest={{ heka_hekad_etc_dir }}/{{ item.name }}.toml
    owner=0
    group=0
    mode=0644

- name: Install heka configuration (outputs)
  tags: heka
  notify: service restart hekad
  with_items: heka_outputs
  template:
    src=hekad_{{ item.type }}.toml.j2
    dest={{ heka_hekad_etc_dir }}/{{ item.name }}.toml
    owner=0
    group=0
    mode=0644


- name: Enable hekad service
  tags: heka
  service:
    enabled=true
    name=hekad

- name: Start hekad service
  tags: heka
  service:
    state=started
    name=hekad
