---
- name: Query RedHat package database for heka
  tags: heka
  register: heka_query_installed_packages
  command: rpm -qa heka

- name: Install heka
  tags: heka
  sudo: yes
  when: '"heka" not in heka_query_installed_packages.stdout'
  command: rpm -ivH {{ util_persistent_data_path_remote }}/{{ heka_install_filename }}

- name: Install hekad service
  tags: heka
  sudo: yes
  notify: service restart hekad
  template:
    src=service_sysvinit.j2
    dest=/etc/init.d/hekad
    owner=0
    group=0
    mode=0755
