---
- name: Query RedHat package database for heka
  tags: heka
  register: heka_query_installed_packages
  command: rpm -qa heka

- name: Install heka
  tags: heka
  become: yes
  when: '"heka" not in heka_query_installed_packages.stdout'
  command: rpm -ivh {{ util_persistent_data_path_remote }}/{{ heka_install_filename }}
