---
- name: Query RedHat package database for heka
  tags: heka
  register: heka_query_installed_packages
  always_run: true
  ignore_errors: true
  failed_when: false
  changed_when: false
  command: rpm -qa heka

- name: Install heka
  tags: heka
  become: true
  when: '"heka" not in heka_query_installed_packages.stdout'
  command: rpm -ivh {{ util_persistent_data_path_remote }}/{{ heka_install_filename }}
