---

- name: Include assets persistency tasks
  taigs: heka
  include: ../../silpion.lib/tasks/datapersistency.yml

- name: Include lib get_url
  tags: heka
  include: ../../silpion.lib/tasks/get_url.yml
  vars:
    url: "{{ heka_mirror }}/v{{ heka_version }}/{{ heka_install_filename }}"
    filename: "{{ heka_install_filename }}"
    sha256sum: "{{ heka_install_filename_sha256sum}}"

- name: Include lib copy
  tags: heka
  include: ../../silpion.lib/tasks/copy.yml
  vars:
    filename: "{{ heka_install_filename }}"
